[env]
# Arbitrary Environment Variables
geniroh_PROJECT_NAME = 'azure-ssh-certs'

[tools]
# Specify tooling versions
python = '3.12.2'
opentofu = '1.8.0-alpha1'

[plugins]
# specify a custom repo url
# note this will only be used if the plugin does not already exist


[settings]
