---
- name: "Accept the host CA"
  tags:
    - accept_host_ca
  vars:
    vault_name: "kv-{{ service_name }}-{{ env }}-{{ site }}"
    secret_name: "kvk-{{ service_name }}-{{ env }}-{{ site }}-{{ ca_type }}-{{ ca_key_type }}"
    resource_group_name: "rg-{{ service_name }}-{{ env }}-{{ site }}"
    user_ssh_key_filename: "{{ user }}-{{ env }}-{{ site }}"

  block:
    - name: "Retrieving secrets using Azure"
      when:
        - use_azure is defined
        - use_azure
      block:
        - name: Get Key Vault by name
          azure.azcollection.azure_rm_keyvault_info:
            resource_group: "{{ resource_group_name }}"
            name: "{{ vault_name }}"
          register: key_vault_attrs

        - name: Set key vault URI fact
          set_fact:
            key_vault_uri: "{{ key_vault_attrs['keyvaults'][0]['vault_uri'] }}"

        - name: Get secret value
          azure.azcollection.azure_rm_keyvaultsecret_info:
            vault_uri: "{{ key_vault_uri }}"
            name: "{{ secret_name }}"
          register: ssh_key_attrs

        - name: Set secret fact
          ansible.builtin.set_fact:
            ssh_key: "{{ ssh_key_attrs.secrets[0].secret }}"

      rescue:
        - name: "Getting secrets from Azure failed"
          ansible.builtin.set_fact:
            task_failed: true

    - name: "Retrieving secrets using BWS"
      when:
        - use_azure is not defined or not use_azure
      block:
        - name: "Get secret value"
          ansible.builtin.set_fact:
            bws_secret_value: "{{ lookup('community.general.bitwarden_secrets_manager', bws_secret_id).value }}"

        # TODO: The single quotes are currently a hack around: https://github.com/sebastiaan-dev/terraform-provider-bitwarden-secrets/issues/5
        - name: "Remove leading and trailing single quotes from bws_secret_value"
          ansible.builtin.set_fact:
            ssh_key: '{{ bws_secret_value | regex_replace("^''|''$", '''', multiline=True) }}'

      rescue:
        - name: "Getting secrets from BWS failed"
          ansible.builtin.set_fact:
            task_failed: true

    - name: Create secret CA private keytmp file with only my access
      ansible.builtin.tempfile:
        state: file
        suffix: _ca_private_key
      register: ssh_key_file

    - name: Ensure file is only readable by me
      ansible.builtin.file:
        path: "{{ ssh_key_file.path }}"
        mode: 0600

    - name: Add cert authority for hostkey checking
      ansible.builtin.lineinfile:
        state: present
        dest: "~/.ssh/known_hosts"
        line: "@cert-authority {{ domain }} {{ ssh_key }}"
        search_string: "@cert-authority {{ domain }}"

    - name: Add a host in the configuration
      community.general.ssh_config:
        ssh_config_file: "~/.ssh/config"
        strict_host_key_checking: "yes"
        remote_user: root
        host: "{{ domain }}"
        identity_file: "~/.ssh/{{ user_ssh_key_filename }}"
        state: present
        add_keys_to_agent: true
        controlmaster: auto # Since we use ansible quite a bit
        controlpersist: 600
        forward_agent: false # We generally dont need this and adds a security risk
  rescue:
    - name: "Configuring to accept Host CA failed"
      ansible.builtin.set_fact:
        task_failed: true
