---
- name: "Pre tasks"
  hosts: all
  pre_tasks:
    - name: Verify Ansible is version 2.11 or above. (If this fails you may need to update Ansible)
      assert:
        that: "ansible_version.full is version_compare('2.11', '>=')"
        msg: >
          "Ansible is out of date."

- name: "Setup the User Workstation to use SSH certificates"
  hosts: all
  roles:
    - role: sign_user_key
    - role: accept_host_ca
