---
- name: "Accept the user CA certificate"
  tags:
    - accept_user_ca
  vars:
    vault_name: "kv-{{ service_name }}-{{ env }}-{{ site }}"
    secret_name: "kvk-{{ service_name }}-{{ env }}-{{ site }}-{{ ca_type }}-{{ ca_key_type }}"
    resource_group_name: "rg-{{ service_name }}-{{ env }}-{{ site }}"
    ca_public_key_path: "/etc/ssh/{{ secret_name }}.pub"
  block:

    - name: "Retrieving secrets using Azure"
      when:
        - use_azure is defined
        - use_azure
      block:
        - name: Get Key Vault by name
          azure.azcollection.azure_rm_keyvault_info:
            resource_group: "{{ resource_group_name }}"
            name: "{{ vault_name }}"
          register: key_vault_attrs
          delegate_to: localhost

        - name: Set key vault URI fact
          set_fact:
            key_vault_uri: "{{ key_vault_attrs['keyvaults'][0]['vault_uri'] }}"

        - name: Get secret value
          azure.azcollection.azure_rm_keyvaultsecret_info:
            vault_uri: "{{ key_vault_uri }}"
            name: "{{ secret_name }}"
          register: ssh_key_attrs
          delegate_to: localhost

        - name: Set secret fact
          ansible.builtin.set_fact:
            ssh_key: "{{ ssh_key_attrs.secrets[0].secret }}"
      rescue:
        - name: "Getting secrets from Azure failed"
          ansible.builtin.set_fact:
            task_failed: true

    - name: Create secret CA private keytmp file with only my access
      ansible.builtin.tempfile:
        state: file
        suffix: _ca_private_key
      register: ssh_key_file

    - name: Ensure file is only readable by me
      ansible.builtin.lineinfile:
        state: present
        create: true
        path: "{{ ca_public_key_path }}"
        owner: root
        group: root
        line: "{{ ssh_key }}"
        mode: 0600

    - name: Update sshd_config for the new user certificate
      ansible.builtin.lineinfile:
        state: present
        dest: "/etc/ssh/sshd_config"
        line: "TrustedUserCAKeys {{ ca_public_key_path }}"
        insertafter: "HostCertificate"
        search_string: "TrustedUserCAKeys {{ ca_public_key_path }}"

    - name: Restart the sshd daemon
      ansible.builtin.service:
        name: sshd
        state: restarted

  rescue:
    - name: "Configuring to accept User CA failed"
      ansible.builtin.set_fact:
        task_failed: true
