---
- name: "Accept the user CA certificate"
  tags:
    - accept_user_ca
  vars:
    # Azure Implementation
    ca_key_type: "pubopenssh"
    ca_type: "userca"
    vault_name: "kv-{{ service_name }}-{{ env }}-{{ site }}"
    secret_name: "kvk-{{ service_name }}-{{ env }}-{{ site }}-{{ ca_type }}-{{ ca_key_type }}"
    resource_group_name: "rg-{{ service_name }}-{{ env }}-{{ site }}"

    # BWS Implementation
    bws_secret_id: "37dcd427-3069-43ec-b083-b1cf016eb36b"

    # General
    ca_public_key_path: "/etc/ssh/{{ secret_name }}.pub"
  block:
    - name: "Retrieving secrets using Azure"
      when:
        - use_azure is defined
        - use_azure
      block:
        - name: Get Key Vault by name
          azure.azcollection.azure_rm_keyvault_info:
            resource_group: "{{ resource_group_name }}"
            name: "{{ vault_name }}"
          register: key_vault_attrs
          delegate_to: localhost

        - name: Set key vault URI fact
          set_fact:
            key_vault_uri: "{{ key_vault_attrs['keyvaults'][0]['vault_uri'] }}"

        - name: Get secret value
          azure.azcollection.azure_rm_keyvaultsecret_info:
            vault_uri: "{{ key_vault_uri }}"
            name: "{{ secret_name }}"
          register: ssh_key_attrs
          delegate_to: localhost

        - name: Set secret fact
          ansible.builtin.set_fact:
            ssh_key: "{{ ssh_key_attrs.secrets[0].secret }}"
      rescue:
        - name: "Getting secrets from Azure failed"
          ansible.builtin.set_fact:
            task_failed: true

    - name: "Retrieving secrets using BWS"
      when:
        - use_azure is not defined or not use_azure
      block:
        - name: "Get secret value"
          ansible.builtin.set_fact:
            bws_secret_value: "{{ lookup('community.general.bitwarden_secrets_manager', bws_secret_id).value }}"

        # TODO: The single quotes are currently a hack around: https://github.com/sebastiaan-dev/terraform-provider-bitwarden-secrets/issues/5
        - name: "Remove leading and trailing single quotes from bws_secret_value"
          ansible.builtin.set_fact:
            ssh_key: '{{ bws_secret_value | regex_replace("^''|''$", '''', multiline=True) }}'

      rescue:
        - name: "Getting secrets from BWS failed"
          ansible.builtin.set_fact:
            task_failed: true

    - name: Create secret CA private keytmp file with only my access
      ansible.builtin.tempfile:
        state: file
        suffix: _ca_private_key
      register: ssh_key_file

    - name: Remove any existing public key
      ansible.builtin.file:
        path: "{{ ca_public_key_path }}"
        state: absent

    - name: Ensure file is only readable by me
      ansible.builtin.lineinfile:
        state: present
        create: true
        path: "{{ ca_public_key_path }}"
        owner: root
        group: root
        line: "{{ ssh_key }}"
        mode: 0600

    - name: Update sshd_config for the new user certificate
      ansible.builtin.lineinfile:
        state: present
        dest: "/etc/ssh/sshd_config"
        line: "TrustedUserCAKeys {{ ca_public_key_path }}"
        insertafter: "HostCertificate"
        search_string: "TrustedUserCAKeys {{ ca_public_key_path }}"

    - name: Restart the sshd daemon
      ansible.builtin.service:
        name: sshd
        state: restarted

  rescue:
    - name: "Configuring to accept User CA failed"
      ansible.builtin.set_fact:
        task_failed: true
